filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log
    fields:
      type: nginx-access

  - type: log
    enabled: true
    paths:
      - /var/log/nginx/error.log
    fields:
      type: nginx-error

processors:
  - add_fields:
      when.equals:
        fields.type: nginx-access
      target: ""
      fields:
        event.dataset: nginx.access

  - add_fields:
      when.equals:
        fields.type: nginx-error
      target: ""
      fields:
        event.dataset: nginx.error

  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

logging.json: true
logging.metrics.enabled: false
